/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 public/models/room2.gltf -K -k
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Office(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("models/office.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Dual_Monitors_on_sit-stand_arm"
          position={[-0.412, 1.648, -3.513]}
          rotation={[-Math.PI / 2, 0, 3.117]}
          scale={33.303}
        >
          <mesh
            name="Dual_Monitors_on_sit-stand_arm|group112678593|Dupli|5"
            geometry={
              nodes["Dual_Monitors_on_sit-stand_arm|group112678593|Dupli|5"]
                .geometry
            }
            material={materials["mat22.010"]}
          />
          <mesh
            name="Dual_Monitors_on_sit-stand_arm|group1219313228|Dupli|2"
            geometry={
              nodes["Dual_Monitors_on_sit-stand_arm|group1219313228|Dupli|2"]
                .geometry
            }
            material={materials["mat22.010"]}
          />
          <mesh
            name="Dual_Monitors_on_sit-stand_arm|group1462626064|Dupli|7"
            geometry={
              nodes["Dual_Monitors_on_sit-stand_arm|group1462626064|Dupli|7"]
                .geometry
            }
            material={materials["mat22.010"]}
          />
          <group
            name="Dual_Monitors_on_sit-stand_arm|group150401702|Dupli|15"
            position={[0, 0, -0.007]}
            scale={1.043}
          >
            <mesh
              name="Dual_Monitors_on_sit-stand_arm|group150401702|Dupli|15_1"
              geometry={
                nodes[
                  "Dual_Monitors_on_sit-stand_arm|group150401702|Dupli|15_1"
                ].geometry
              }
              material={materials["mat22.010"]}
            />
            <mesh
              name="Dual_Monitors_on_sit-stand_arm|group150401702|Dupli|15_2"
              geometry={
                nodes[
                  "Dual_Monitors_on_sit-stand_arm|group150401702|Dupli|15_2"
                ].geometry
              }
              material={materials["mat23.015"]}
            />
          </group>
          <mesh
            name="Dual_Monitors_on_sit-stand_arm|group1658787459|Dupli|18"
            geometry={
              nodes["Dual_Monitors_on_sit-stand_arm|group1658787459|Dupli|18"]
                .geometry
            }
            material={materials["mat22.010"]}
          />
          <group name="Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23">
            <mesh
              name="Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23_1"
              geometry={
                nodes[
                  "Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23_1"
                ].geometry
              }
              material={materials["mat22.010"]}
            />
            <mesh
              name="Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23_2"
              geometry={
                nodes[
                  "Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23_2"
                ].geometry
              }
              material={materials["mat23.015"]}
            />
            <mesh
              name="Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23_3"
              geometry={
                nodes[
                  "Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23_3"
                ].geometry
              }
              material={materials["mat21.012"]}
            />
          </group>
          <mesh
            name="Dual_Monitors_on_sit-stand_arm|group1698824667|Dupli|12"
            geometry={
              nodes["Dual_Monitors_on_sit-stand_arm|group1698824667|Dupli|12"]
                .geometry
            }
            material={materials["mat22.010"]}
          />
          <mesh
            name="Dual_Monitors_on_sit-stand_arm|group1746518091|Dupli|8"
            geometry={
              nodes["Dual_Monitors_on_sit-stand_arm|group1746518091|Dupli|8"]
                .geometry
            }
            material={materials["mat23.015"]}
          />
          <mesh
            name="Dual_Monitors_on_sit-stand_arm|group1783798096|Dupli|3"
            geometry={
              nodes["Dual_Monitors_on_sit-stand_arm|group1783798096|Dupli|3"]
                .geometry
            }
            material={materials["mat23.015"]}
          />
          <mesh
            name="Dual_Monitors_on_sit-stand_arm|group1896072715|Dupli|19"
            geometry={
              nodes["Dual_Monitors_on_sit-stand_arm|group1896072715|Dupli|19"]
                .geometry
            }
            material={materials["mat22.010"]}
          />
          <mesh
            name="Dual_Monitors_on_sit-stand_arm|group2060347243|Dupli|9"
            geometry={
              nodes["Dual_Monitors_on_sit-stand_arm|group2060347243|Dupli|9"]
                .geometry
            }
            material={materials["mat22.010"]}
          />
          <mesh
            name="Dual_Monitors_on_sit-stand_arm|group2063576334|Dupli|11"
            geometry={
              nodes["Dual_Monitors_on_sit-stand_arm|group2063576334|Dupli|11"]
                .geometry
            }
            material={materials["mat22.010"]}
          />
          <mesh
            name="Dual_Monitors_on_sit-stand_arm|group2070617275|Dupli|13"
            geometry={
              nodes["Dual_Monitors_on_sit-stand_arm|group2070617275|Dupli|13"]
                .geometry
            }
            material={materials["mat23.015"]}
          />
          <mesh
            name="Dual_Monitors_on_sit-stand_arm|group2128326706|Dupli|16"
            geometry={
              nodes["Dual_Monitors_on_sit-stand_arm|group2128326706|Dupli|16"]
                .geometry
            }
            material={materials["mat23.015"]}
          />
          <group name="Dual_Monitors_on_sit-stand_arm|group329542522|Dupli|">
            <mesh
              name="Dual_Monitors_on_sit-stand_arm|group329542522|Dupli|_1"
              geometry={
                nodes["Dual_Monitors_on_sit-stand_arm|group329542522|Dupli|_1"]
                  .geometry
              }
              material={materials["mat22.010"]}
            />
            <mesh
              name="Dual_Monitors_on_sit-stand_arm|group329542522|Dupli|_2"
              geometry={
                nodes["Dual_Monitors_on_sit-stand_arm|group329542522|Dupli|_2"]
                  .geometry
              }
              material={materials["mat23.015"]}
            />
          </group>
          <mesh
            name="Dual_Monitors_on_sit-stand_arm|group451364077|Dupli|20"
            geometry={
              nodes["Dual_Monitors_on_sit-stand_arm|group451364077|Dupli|20"]
                .geometry
            }
            material={materials["mat22.010"]}
          />
          <mesh
            name="Dual_Monitors_on_sit-stand_arm|group575146565|Dupli|6"
            geometry={
              nodes["Dual_Monitors_on_sit-stand_arm|group575146565|Dupli|6"]
                .geometry
            }
            material={materials["mat22.010"]}
          />
          <group name="Dual_Monitors_on_sit-stand_arm|group576947092|Dupli|1">
            <mesh
              name="Dual_Monitors_on_sit-stand_arm|group576947092|Dupli|1_1"
              geometry={
                nodes["Dual_Monitors_on_sit-stand_arm|group576947092|Dupli|1_1"]
                  .geometry
              }
              material={materials["mat22.010"]}
            />
            <mesh
              name="Dual_Monitors_on_sit-stand_arm|group576947092|Dupli|1_2"
              geometry={
                nodes["Dual_Monitors_on_sit-stand_arm|group576947092|Dupli|1_2"]
                  .geometry
              }
              material={materials["mat23.015"]}
            />
          </group>
          <mesh
            name="Dual_Monitors_on_sit-stand_arm|group625259463|Dupli|4"
            geometry={
              nodes["Dual_Monitors_on_sit-stand_arm|group625259463|Dupli|4"]
                .geometry
            }
            material={materials["mat23.015"]}
          />
          <mesh
            name="Dual_Monitors_on_sit-stand_arm|group710626981|Dupli|14"
            geometry={
              nodes["Dual_Monitors_on_sit-stand_arm|group710626981|Dupli|14"]
                .geometry
            }
            material={materials["mat22.010"]}
          />
          <mesh
            name="Dual_Monitors_on_sit-stand_arm|group786212531|Dupli|21"
            geometry={
              nodes["Dual_Monitors_on_sit-stand_arm|group786212531|Dupli|21"]
                .geometry
            }
            material={materials["mat22.010"]}
          />
          <group name="Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22">
            <mesh
              name="Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22_1"
              geometry={
                nodes[
                  "Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22_1"
                ].geometry
              }
              material={materials["mat22.010"]}
            />
            <mesh
              name="Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22_2"
              geometry={
                nodes[
                  "Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22_2"
                ].geometry
              }
              material={materials["mat23.015"]}
            />
            <mesh
              name="Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22_3"
              geometry={
                nodes[
                  "Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22_3"
                ].geometry
              }
              material={materials["mat21.012"]}
            />
          </group>
          <mesh
            name="Dual_Monitors_on_sit-stand_arm|group929043094|Dupli|10"
            geometry={
              nodes["Dual_Monitors_on_sit-stand_arm|group929043094|Dupli|10"]
                .geometry
            }
            material={materials["mat22.010"]}
          />
          <mesh
            name="Dual_Monitors_on_sit-stand_arm|group974294459|Dupli|17"
            geometry={
              nodes["Dual_Monitors_on_sit-stand_arm|group974294459|Dupli|17"]
                .geometry
            }
            material={materials["mat23.015"]}
            position={[0, -0.004, -0.007]}
            scale={1.336}
          />
        </group>
        <group
          name="Keyboard"
          position={[-0.433, 1.234, -3.095]}
          rotation={[-1.565, 0.001, -0.064]}
          scale={23.602}
        >
          <mesh
            name="Keyboard|group1030983910|Dupli|22"
            geometry={nodes["Keyboard|group1030983910|Dupli|22"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group1075691498|Dupli|58"
            geometry={nodes["Keyboard|group1075691498|Dupli|58"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group1149852049|Dupli|53"
            geometry={nodes["Keyboard|group1149852049|Dupli|53"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group1152190519|Dupli|19"
            geometry={nodes["Keyboard|group1152190519|Dupli|19"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group1180881246|Dupli|50"
            geometry={nodes["Keyboard|group1180881246|Dupli|50"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group1238060299|Dupli|28"
            geometry={nodes["Keyboard|group1238060299|Dupli|28"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group1238428394|Dupli|61"
            geometry={nodes["Keyboard|group1238428394|Dupli|61"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group1272091893|Dupli|35"
            geometry={nodes["Keyboard|group1272091893|Dupli|35"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group1316349499|Dupli|39"
            geometry={nodes["Keyboard|group1316349499|Dupli|39"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group1323238240|Dupli|32"
            geometry={nodes["Keyboard|group1323238240|Dupli|32"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group145618305|Dupli|23"
            geometry={nodes["Keyboard|group145618305|Dupli|23"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group1486350934|Dupli|63"
            geometry={nodes["Keyboard|group1486350934|Dupli|63"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group150579309|Dupli|11"
            geometry={nodes["Keyboard|group150579309|Dupli|11"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group1529968652|Dupli|6"
            geometry={nodes["Keyboard|group1529968652|Dupli|6"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group1571332333|Dupli|33"
            geometry={nodes["Keyboard|group1571332333|Dupli|33"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group1581414308|Dupli|8"
            geometry={nodes["Keyboard|group1581414308|Dupli|8"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group1589752359|Dupli|26"
            geometry={nodes["Keyboard|group1589752359|Dupli|26"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group1629393722|Dupli|64"
            geometry={nodes["Keyboard|group1629393722|Dupli|64"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group1629609685|Dupli|21"
            geometry={nodes["Keyboard|group1629609685|Dupli|21"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group1675960081|Dupli|12"
            geometry={nodes["Keyboard|group1675960081|Dupli|12"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group1740918352|Dupli|46"
            geometry={nodes["Keyboard|group1740918352|Dupli|46"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group1753917514|Dupli|5"
            geometry={nodes["Keyboard|group1753917514|Dupli|5"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group1754683637|Dupli|40"
            geometry={nodes["Keyboard|group1754683637|Dupli|40"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group1764140354|Dupli|60"
            geometry={nodes["Keyboard|group1764140354|Dupli|60"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group1870575723|Dupli|65"
            geometry={nodes["Keyboard|group1870575723|Dupli|65"].geometry}
            material={materials["mat16.006"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group1899843208|Dupli|36"
            geometry={nodes["Keyboard|group1899843208|Dupli|36"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group1956214489|Dupli|14"
            geometry={nodes["Keyboard|group1956214489|Dupli|14"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group196400395|Dupli|15"
            geometry={nodes["Keyboard|group196400395|Dupli|15"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group1976194690|Dupli|18"
            geometry={nodes["Keyboard|group1976194690|Dupli|18"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group205302596|Dupli|31"
            geometry={nodes["Keyboard|group205302596|Dupli|31"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group2074153597|Dupli|20"
            geometry={nodes["Keyboard|group2074153597|Dupli|20"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group2085389804|Dupli|57"
            geometry={nodes["Keyboard|group2085389804|Dupli|57"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group2091112366|Dupli|59"
            geometry={nodes["Keyboard|group2091112366|Dupli|59"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group2106755496|Dupli|4"
            geometry={nodes["Keyboard|group2106755496|Dupli|4"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group2146178072|Dupli|38"
            geometry={nodes["Keyboard|group2146178072|Dupli|38"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group252681800|Dupli|7"
            geometry={nodes["Keyboard|group252681800|Dupli|7"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group268332703|Dupli|44"
            geometry={nodes["Keyboard|group268332703|Dupli|44"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group287159489|Dupli|13"
            geometry={nodes["Keyboard|group287159489|Dupli|13"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group295085766|Dupli|9"
            geometry={nodes["Keyboard|group295085766|Dupli|9"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group311988427|Dupli|1"
            geometry={nodes["Keyboard|group311988427|Dupli|1"].geometry}
            material={materials["mat22.011"]}
            position={[0, 0, -0.001]}
          />
          <mesh
            name="Keyboard|group34220672|Dupli|34"
            geometry={nodes["Keyboard|group34220672|Dupli|34"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group384612072|Dupli|10"
            geometry={nodes["Keyboard|group384612072|Dupli|10"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group418912012|Dupli|30"
            geometry={nodes["Keyboard|group418912012|Dupli|30"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group42243725|Dupli|37"
            geometry={nodes["Keyboard|group42243725|Dupli|37"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group425587018|Dupli|"
            geometry={nodes["Keyboard|group425587018|Dupli|"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group449779970|Dupli|3"
            geometry={nodes["Keyboard|group449779970|Dupli|3"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group45382983|Dupli|52"
            geometry={nodes["Keyboard|group45382983|Dupli|52"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group475225180|Dupli|41"
            geometry={nodes["Keyboard|group475225180|Dupli|41"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group573547017|Dupli|49"
            geometry={nodes["Keyboard|group573547017|Dupli|49"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group588539140|Dupli|47"
            geometry={nodes["Keyboard|group588539140|Dupli|47"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group601803475|Dupli|25"
            geometry={nodes["Keyboard|group601803475|Dupli|25"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group616518658|Dupli|56"
            geometry={nodes["Keyboard|group616518658|Dupli|56"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group687259746|Dupli|51"
            geometry={nodes["Keyboard|group687259746|Dupli|51"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group706802639|Dupli|17"
            geometry={nodes["Keyboard|group706802639|Dupli|17"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group729811280|Dupli|48"
            geometry={nodes["Keyboard|group729811280|Dupli|48"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group77921105|Dupli|42"
            geometry={nodes["Keyboard|group77921105|Dupli|42"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group790925258|Dupli|54"
            geometry={nodes["Keyboard|group790925258|Dupli|54"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group801095923|Dupli|29"
            geometry={nodes["Keyboard|group801095923|Dupli|29"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group806343109|Dupli|27"
            geometry={nodes["Keyboard|group806343109|Dupli|27"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group826580911|Dupli|24"
            geometry={nodes["Keyboard|group826580911|Dupli|24"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group873458270|Dupli|55"
            geometry={nodes["Keyboard|group873458270|Dupli|55"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group873558583|Dupli|62"
            geometry={nodes["Keyboard|group873558583|Dupli|62"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group877249531|Dupli|66"
            geometry={nodes["Keyboard|group877249531|Dupli|66"].geometry}
            material={materials["mat9.002"]}
          />
          <mesh
            name="Keyboard|group954813675|Dupli|16"
            geometry={nodes["Keyboard|group954813675|Dupli|16"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group96314515|Dupli|2"
            geometry={nodes["Keyboard|group96314515|Dupli|2"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group96968687|Dupli|43"
            geometry={nodes["Keyboard|group96968687|Dupli|43"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
          <mesh
            name="Keyboard|group993315105|Dupli|45"
            geometry={nodes["Keyboard|group993315105|Dupli|45"].geometry}
            material={materials["mat21.013"]}
            position={[0, 0, -0.001]}
            scale={1.281}
          />
        </group>
        <group
          name="Mug_With_Office_Tool"
          position={[0.159, 1.182, -3.755]}
          rotation={[-Math.PI / 2, 0, 3.117]}
          scale={143.015}
        >
          <mesh
            name="Mug_With_Office_Tool|Mug_with_office_tools|Dupli|"
            geometry={
              nodes["Mug_With_Office_Tool|Mug_with_office_tools|Dupli|"]
                .geometry
            }
            material={materials["Material.015"]}
            scale={100}
          />
        </group>
        <group
          name="Soda001"
          position={[0.54, 1.187, -3.283]}
          rotation={[-Math.PI / 2, 0, 3.117]}
          scale={20.551}
        >
          <group
            name="Soda001|Soda|Dupli|"
            position={[-0.001, 0, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              name="Soda001|Soda|Dupli|_1"
              geometry={nodes["Soda001|Soda|Dupli|_1"].geometry}
              material={materials["White.005"]}
            />
            <mesh
              name="Soda001|Soda|Dupli|_2"
              geometry={nodes["Soda001|Soda|Dupli|_2"].geometry}
              material={materials["Red.002"]}
            />
          </group>
        </group>
        <group
          name="Notebook"
          position={[-1.021, 1.067, -7.456]}
          rotation={[-Math.PI / 2, 0, 0.26]}
          scale={3.419}
        >
          <group
            name="Notebook|Notebook_Cube041|Dupli|"
            position={[-0.309, -1.158, 0.035]}
          >
            <mesh
              name="Notebook|Notebook_Cube041|Dupli|_1"
              geometry={nodes["Notebook|Notebook_Cube041|Dupli|_1"].geometry}
              material={materials["FFEB3B.002"]}
            />
            <mesh
              name="Notebook|Notebook_Cube041|Dupli|_2"
              geometry={nodes["Notebook|Notebook_Cube041|Dupli|_2"].geometry}
              material={materials["795548.003"]}
            />
            <mesh
              name="Notebook|Notebook_Cube041|Dupli|_3"
              geometry={nodes["Notebook|Notebook_Cube041|Dupli|_3"].geometry}
              material={materials["F44336.006"]}
            />
          </group>
        </group>
        <group
          name="RootNode001"
          position={[0, 0.658, -0.801]}
          rotation={[-Math.PI, 0.1, -Math.PI]}
          scale={2.355}
        />
        <group
          name="RootNode002"
          position={[0.129, 0.272, -2.535]}
          scale={1.768}
        >
          <mesh
            name="Trashbin"
            geometry={nodes.Trashbin.geometry}
            material={materials["Material.002"]}
            position={[0.219, -0.134, -0.541]}
            scale={100}
          />
        </group>
        <group
          name="RootNode003"
          position={[-0.34, 0.247, -0.92]}
          rotation={[Math.PI, -0.31, Math.PI]}
          scale={1.437}
        >
          <group
            name="OfficeChair"
            position={[-0.251, -0.139, 0.939]}
            rotation={[-1.597, 0.016, -0.388]}
            scale={100}
          >
            <mesh
              name="OfficeChair_1"
              geometry={nodes.OfficeChair_1.geometry}
              material={materials.Grey}
            />
            <mesh
              name="OfficeChair_2"
              geometry={nodes.OfficeChair_2.geometry}
              material={materials.Black}
            />
            <mesh
              name="OfficeChair_3"
              geometry={nodes.OfficeChair_3.geometry}
              material={materials.Chair}
            />
          </group>
        </group>
        <group
          name="RootNode005"
          position={[-2.611, 0.939, -4.05]}
          scale={1.574}
        >
          <group name="Shelf_Clutter" scale={100}>
            <mesh
              name="Shelf_Clutter_1"
              geometry={nodes.Shelf_Clutter_1.geometry}
              material={materials.mat22}
            />
            <mesh
              name="Shelf_Clutter_2"
              geometry={nodes.Shelf_Clutter_2.geometry}
              material={materials.mat17}
            />
            <mesh
              name="Shelf_Clutter_3"
              geometry={nodes.Shelf_Clutter_3.geometry}
              material={materials.mat15}
            />
            <mesh
              name="Shelf_Clutter_4"
              geometry={nodes.Shelf_Clutter_4.geometry}
              material={materials.mat1}
            />
            <mesh
              name="Shelf_Clutter_5"
              geometry={nodes.Shelf_Clutter_5.geometry}
              material={materials["mat21.005"]}
            />
            <mesh
              name="Shelf_Clutter_6"
              geometry={nodes.Shelf_Clutter_6.geometry}
              material={materials.mat11}
            />
            <mesh
              name="Shelf_Clutter_7"
              geometry={nodes.Shelf_Clutter_7.geometry}
              material={materials["mat20.003"]}
            />
            <mesh
              name="Shelf_Clutter_8"
              geometry={nodes.Shelf_Clutter_8.geometry}
              material={materials.mat16}
            />
            <mesh
              name="Shelf_Clutter_9"
              geometry={nodes.Shelf_Clutter_9.geometry}
              material={materials.mat24}
            />
            <mesh
              name="Shelf_Clutter_10"
              geometry={nodes.Shelf_Clutter_10.geometry}
              material={materials["mat8.003"]}
            />
            <mesh
              name="Shelf_Clutter_11"
              geometry={nodes.Shelf_Clutter_11.geometry}
              material={materials["mat23.002"]}
            />
            <mesh
              name="Shelf_Clutter_12"
              geometry={nodes.Shelf_Clutter_12.geometry}
              material={materials.mat7}
            />
            <mesh
              name="Shelf_Clutter_13"
              geometry={nodes.Shelf_Clutter_13.geometry}
              material={materials.mat12}
            />
            <mesh
              name="Shelf_Clutter_14"
              geometry={nodes.Shelf_Clutter_14.geometry}
              material={materials.mat4}
            />
            <mesh
              name="Shelf_Clutter_15"
              geometry={nodes.Shelf_Clutter_15.geometry}
              material={materials.mat10}
            />
          </group>
        </group>
        <group
          name="RootNode006"
          position={[1.744, 0, 1.704]}
          rotation={[Math.PI, -0.034, Math.PI]}
        >
          <group
            name="Couch_Small1"
            position={[1.334, 0, 0.986]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              name="Couch_Small1_1"
              geometry={nodes.Couch_Small1_1.geometry}
              material={materials.Couch_Blue}
            />
            <mesh
              name="Couch_Small1_2"
              geometry={nodes.Couch_Small1_2.geometry}
              material={materials["Black.002"]}
            />
          </group>
        </group>
        <group
          name="Empty"
          position={[-0.433, 0.058, -2.164]}
          rotation={[-Math.PI, 0.289, -Math.PI]}
          scale={1.453}
        >
          <group name="Armature">
            <primitive object={nodes.Hips} />
            {/* <skinnedMesh name="Wolf3D_Body" geometry={nodes.Wolf3D_Body.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Wolf3D_Body.skeleton} />
            <skinnedMesh name="Wolf3D_Glasses" geometry={nodes.Wolf3D_Glasses.geometry} material={materials.Wolf3D_Glasses} skeleton={nodes.Wolf3D_Glasses.skeleton} />
            <skinnedMesh name="Wolf3D_Hair" geometry={nodes.Wolf3D_Hair.geometry} material={materials.Wolf3D_Hair} skeleton={nodes.Wolf3D_Hair.skeleton} />
            <skinnedMesh name="Wolf3D_Outfit_Bottom" geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />
            <skinnedMesh name="Wolf3D_Outfit_Footwear" geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />
            <skinnedMesh name="Wolf3D_Outfit_Top" geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />
            <skinnedMesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeLeft.skeleton} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} />
            <skinnedMesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeRight.skeleton} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} />
            <skinnedMesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Wolf3D_Head.skeleton} morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences} />
            <skinnedMesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.Wolf3D_Teeth.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences} /> */}
          </group>
        </group>
        <mesh
          name="Mousepad001"
          geometry={nodes.Mousepad001.geometry}
          material={materials.Mousepad}
          position={[0.559, 1.19, -2.943]}
          rotation={[-Math.PI / 2, 0, -1.595]}
          scale={[19.008, 23.14, 0.251]}
        />
        <group
          name="Office_Phone001"
          position={[-1.104, 1.262, -3.694]}
          rotation={[Math.PI, -0.12, 0]}
          scale={[862.207, 862.206, 862.206]}
        >
          <mesh
            name="Office_Phone001_1"
            geometry={nodes.Office_Phone001_1.geometry}
            material={materials["Light grey"]}
          />
          <mesh
            name="Office_Phone001_2"
            geometry={nodes.Office_Phone001_2.geometry}
            material={materials["Grey Plastic"]}
          />
          <mesh
            name="Office_Phone001_3"
            geometry={nodes.Office_Phone001_3.geometry}
            material={materials.Screen}
          />
          <mesh
            name="Office_Phone001_4"
            geometry={nodes.Office_Phone001_4.geometry}
            material={materials["Dark Grey Plastic"]}
          />
        </group>
        <group
          name="Calendar-8GqQAqxi3qk"
          position={[0.483, 1.187, -3.679]}
          rotation={[-Math.PI / 2, 0, -0.413]}
          scale={1.371}
        >
          <mesh
            name="Calendar-8GqQAqxi3qk_1"
            geometry={nodes["Calendar-8GqQAqxi3qk_1"].geometry}
            material={materials.Calendar_Texture}
          />
          <mesh
            name="Calendar-8GqQAqxi3qk_2"
            geometry={nodes["Calendar-8GqQAqxi3qk_2"].geometry}
            material={materials.Calendar_Aquamarine}
          />
          <mesh
            name="Calendar-8GqQAqxi3qk_3"
            geometry={nodes["Calendar-8GqQAqxi3qk_3"].geometry}
            material={materials.Calendar_Ivory}
          />
          <mesh
            name="Calendar-8GqQAqxi3qk_4"
            geometry={nodes["Calendar-8GqQAqxi3qk_4"].geometry}
            material={materials.FrontColor}
          />
        </group>
        <group
          name="Desk"
          position={[-0.11, 0.058, -3.423]}
          rotation={[-Math.PI / 2, 0, -1.598]}
          scale={119.278}
        >
          <mesh
            name="Desk_1"
            geometry={nodes.Desk_1.geometry}
            material={materials["BlackCoatSteel.001"]}
          />
          <mesh
            name="Desk_2"
            geometry={nodes.Desk_2.geometry}
            material={materials["GrayPlastic.001"]}
          />
          <mesh
            name="Desk_3"
            geometry={nodes.Desk_3.geometry}
            material={materials["WhiteSteelScrew.001"]}
          />
          <mesh
            name="Desk_4"
            geometry={nodes.Desk_4.geometry}
            material={materials["BlackPlastic.001"]}
          />
          <mesh
            name="Desk_5"
            geometry={nodes.Desk_5.geometry}
            material={materials["BlackWood.001"]}
          />
        </group>
        <mesh
          name="Mouse001"
          geometry={nodes.Mouse001.geometry}
          material={materials["Material.001"]}
          position={[0.547, 1.198, -2.95]}
          rotation={[-Math.PI / 2, 0, 0.427]}
          scale={[17789.332, 17789.328, 17789.332]}
        />
        <mesh
          name="FiddleleafFigPottedPlant_mesh"
          geometry={nodes.FiddleleafFigPottedPlant_mesh.geometry}
          material={materials.FiddleleafFigPottedPlant_mat}
          position={[2.311, 0.034, -3.802]}
          scale={0.18}
        />
        <mesh
          name="Geo_Duck"
          geometry={nodes.Geo_Duck.geometry}
          material={materials.lambert2SG}
          position={[0.58, 1.734, 0.085]}
          rotation={[Math.PI, -0.235, Math.PI]}
          scale={0.018}
        />
        <group
          name="Node"
          position={[-3.907, 1.28, -0.912]}
          rotation={[0, -1.525, 0]}
          scale={2.113}
        >
          <mesh
            name="Node-Mesh"
            geometry={nodes["Node-Mesh"].geometry}
            material={materials["mat16.002"]}
          />
          <mesh
            name="Node-Mesh_1"
            geometry={nodes["Node-Mesh_1"].geometry}
            material={materials["mat24.001"]}
          />
          <mesh
            name="Node-Mesh_2"
            geometry={nodes["Node-Mesh_2"].geometry}
            material={materials.mat23}
          />
          <mesh
            name="Node-Mesh_3"
            geometry={nodes["Node-Mesh_3"].geometry}
            material={materials["mat18.001"]}
          />
          <mesh
            name="Node-Mesh_4"
            geometry={nodes["Node-Mesh_4"].geometry}
            material={materials["mat17.001"]}
          />
          <mesh
            name="Node-Mesh_5"
            geometry={nodes["Node-Mesh_5"].geometry}
            material={materials["mat10.001"]}
          />
          <mesh
            name="Node-Mesh_6"
            geometry={nodes["Node-Mesh_6"].geometry}
            material={materials.mat13}
          />
        </group>
        <group
          name="Node001"
          position={[-3.852, 0.725, -0.873]}
          rotation={[0, -1.525, 0]}
          scale={1.076}
        >
          <mesh
            name="Node-Mesh001"
            geometry={nodes["Node-Mesh001"].geometry}
            material={materials.mat20}
          />
          <mesh
            name="Node-Mesh001_1"
            geometry={nodes["Node-Mesh001_1"].geometry}
            material={materials["mat15.001"]}
          />
        </group>
        <group
          name="group299629432"
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        >
          <mesh
            name="mesh299629432"
            geometry={nodes.mesh299629432.geometry}
            material={materials["mat21.001"]}
          />
          <mesh
            name="mesh299629432_1"
            geometry={nodes.mesh299629432_1.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh299629432_2"
            geometry={nodes.mesh299629432_2.geometry}
            material={materials["mat23.003"]}
          />
        </group>
        <mesh
          name="group2025041128"
          geometry={nodes.group2025041128.geometry}
          material={materials["mat20.002"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group69949088"
          geometry={nodes.group69949088.geometry}
          material={materials["mat20.002"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1679224903"
          geometry={nodes.group1679224903.geometry}
          material={materials["mat20.002"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group2109960991"
          geometry={nodes.group2109960991.geometry}
          material={materials["mat20.002"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group809002780"
          geometry={nodes.group809002780.geometry}
          material={materials["mat20.002"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1145168611"
          geometry={nodes.group1145168611.geometry}
          material={materials["mat20.002"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1241812226"
          geometry={nodes.group1241812226.geometry}
          material={materials.mat18}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <group
          name="group2105143685"
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        >
          <mesh
            name="mesh2105143685"
            geometry={nodes.mesh2105143685.geometry}
            material={materials["mat22.001"]}
          />
          <mesh
            name="mesh2105143685_1"
            geometry={nodes.mesh2105143685_1.geometry}
            material={materials["mat20.002"]}
          />
        </group>
        <mesh
          name="group881264485"
          geometry={nodes.group881264485.geometry}
          material={materials["mat20.002"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1897619194"
          geometry={nodes.group1897619194.geometry}
          material={materials.mat8}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1945117413"
          geometry={nodes.group1945117413.geometry}
          material={materials.mat8}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group854393655"
          geometry={nodes.group854393655.geometry}
          material={materials.mat8}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1386330300"
          geometry={nodes.group1386330300.geometry}
          material={materials.mat8}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1872090036"
          geometry={nodes.group1872090036.geometry}
          material={materials.mat8}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1289099567"
          geometry={nodes.group1289099567.geometry}
          material={materials.mat8}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group781777267"
          geometry={nodes.group781777267.geometry}
          material={materials["mat20.002"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group270290579"
          geometry={nodes.group270290579.geometry}
          material={materials["mat20.002"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1194450922"
          geometry={nodes.group1194450922.geometry}
          material={materials["mat20.002"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1850418241"
          geometry={nodes.group1850418241.geometry}
          material={materials["mat20.002"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group761545271"
          geometry={nodes.group761545271.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1029975216"
          geometry={nodes.group1029975216.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group607112830"
          geometry={nodes.group607112830.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1125642181"
          geometry={nodes.group1125642181.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group926419401"
          geometry={nodes.group926419401.geometry}
          material={materials["mat20.002"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1292753415"
          geometry={nodes.group1292753415.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1846723882"
          geometry={nodes.group1846723882.geometry}
          material={materials["mat21.001"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1796784100"
          geometry={nodes.group1796784100.geometry}
          material={materials["mat21.001"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <group
          name="group530149436"
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        >
          <mesh
            name="mesh530149436"
            geometry={nodes.mesh530149436.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh530149436_1"
            geometry={nodes.mesh530149436_1.geometry}
            material={materials["mat16.001"]}
          />
        </group>
        <mesh
          name="group204683259"
          geometry={nodes.group204683259.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group997271847"
          geometry={nodes.group997271847.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1226234745"
          geometry={nodes.group1226234745.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1428811968"
          geometry={nodes.group1428811968.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1026035939"
          geometry={nodes.group1026035939.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group394553688"
          geometry={nodes.group394553688.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1212017664"
          geometry={nodes.group1212017664.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group385879765"
          geometry={nodes.group385879765.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group2112898328"
          geometry={nodes.group2112898328.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1644354296"
          geometry={nodes.group1644354296.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group658796396"
          geometry={nodes.group658796396.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group985485281"
          geometry={nodes.group985485281.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1637630204"
          geometry={nodes.group1637630204.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group2038571648"
          geometry={nodes.group2038571648.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group350548752"
          geometry={nodes.group350548752.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1842447878"
          geometry={nodes.group1842447878.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group109931803"
          geometry={nodes.group109931803.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group952035642"
          geometry={nodes.group952035642.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group608453808"
          geometry={nodes.group608453808.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group908253510"
          geometry={nodes.group908253510.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1477466730"
          geometry={nodes.group1477466730.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1220067447"
          geometry={nodes.group1220067447.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1979011973"
          geometry={nodes.group1979011973.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1786796470"
          geometry={nodes.group1786796470.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group36083554"
          geometry={nodes.group36083554.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group402995636"
          geometry={nodes.group402995636.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group320194922"
          geometry={nodes.group320194922.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group509719028"
          geometry={nodes.group509719028.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group887340044"
          geometry={nodes.group887340044.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1801924435"
          geometry={nodes.group1801924435.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group920738086"
          geometry={nodes.group920738086.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group493441967"
          geometry={nodes.group493441967.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group2139433864"
          geometry={nodes.group2139433864.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group554351439"
          geometry={nodes.group554351439.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group1608270742"
          geometry={nodes.group1608270742.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="group255800760"
          geometry={nodes.group255800760.geometry}
          material={materials["mat23.003"]}
          position={[2.917, 1.429, 0.684]}
          rotation={[0, 0.412, 0]}
          scale={1.146}
        />
        <mesh
          name="Cube002"
          geometry={nodes.Cube002.geometry}
          material={materials.phong1SG}
          position={[-0.306, 0, -1.148]}
          scale={4.483}
        />
        <mesh
          name="FiddleleafFigPottedPlant_mesh001"
          geometry={nodes.FiddleleafFigPottedPlant_mesh001.geometry}
          material={materials["FiddleleafFigPottedPlant_mat.001"]}
          position={[-2.73, 0.034, 1.273]}
          scale={0.18}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/room2.gltf");
