/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 public/models/office.gltf -K -k
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/office.gltf')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="RootNode" position={[-0.546, 0.064, -12.851]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={1.433}>
          <group name="Dual_Monitors_on_sit-stand_arm" position={[-0.294, 1.36, -6.337]} rotation={[-Math.PI / 2, 0, 0]} scale={30.19}>
            <mesh name="Dual_Monitors_on_sit-stand_arm|group112678593|Dupli|5" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group112678593|Dupli|5'].geometry} material={materials['mat22.010']} />
            <mesh name="Dual_Monitors_on_sit-stand_arm|group1219313228|Dupli|2" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1219313228|Dupli|2'].geometry} material={materials['mat22.010']} />
            <mesh name="Dual_Monitors_on_sit-stand_arm|group1462626064|Dupli|7" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1462626064|Dupli|7'].geometry} material={materials['mat22.010']} />
            <group name="Dual_Monitors_on_sit-stand_arm|group150401702|Dupli|15" position={[0, 0, -0.008]}>
              <mesh name="Dual_Monitors_on_sit-stand_arm|group150401702|Dupli|15_1" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group150401702|Dupli|15_1'].geometry} material={materials['mat22.010']} />
              <mesh name="Dual_Monitors_on_sit-stand_arm|group150401702|Dupli|15_2" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group150401702|Dupli|15_2'].geometry} material={materials['mat23.015']} />
            </group>
            <mesh name="Dual_Monitors_on_sit-stand_arm|group1658787459|Dupli|18" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1658787459|Dupli|18'].geometry} material={materials['mat22.010']} />
            <group name="Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23">
              <mesh name="Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23_1" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23_1'].geometry} material={materials['mat22.010']} />
              <mesh name="Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23_2" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23_2'].geometry} material={materials['mat23.015']} />
              <mesh name="Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23_3" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23_3'].geometry} material={materials['mat21.012']} />
            </group>
            <mesh name="Dual_Monitors_on_sit-stand_arm|group1698824667|Dupli|12" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1698824667|Dupli|12'].geometry} material={materials['mat22.010']} />
            <mesh name="Dual_Monitors_on_sit-stand_arm|group1746518091|Dupli|8" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1746518091|Dupli|8'].geometry} material={materials['mat23.015']} />
            <mesh name="Dual_Monitors_on_sit-stand_arm|group1783798096|Dupli|3" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1783798096|Dupli|3'].geometry} material={materials['mat23.015']} />
            <mesh name="Dual_Monitors_on_sit-stand_arm|group1896072715|Dupli|19" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1896072715|Dupli|19'].geometry} material={materials['mat22.010']} />
            <mesh name="Dual_Monitors_on_sit-stand_arm|group2060347243|Dupli|9" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group2060347243|Dupli|9'].geometry} material={materials['mat22.010']} />
            <mesh name="Dual_Monitors_on_sit-stand_arm|group2063576334|Dupli|11" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group2063576334|Dupli|11'].geometry} material={materials['mat22.010']} />
            <mesh name="Dual_Monitors_on_sit-stand_arm|group2070617275|Dupli|13" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group2070617275|Dupli|13'].geometry} material={materials['mat23.015']} />
            <mesh name="Dual_Monitors_on_sit-stand_arm|group2128326706|Dupli|16" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group2128326706|Dupli|16'].geometry} material={materials['mat23.015']} />
            <group name="Dual_Monitors_on_sit-stand_arm|group329542522|Dupli|">
              <mesh name="Dual_Monitors_on_sit-stand_arm|group329542522|Dupli|_1" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group329542522|Dupli|_1'].geometry} material={materials['mat22.010']} />
              <mesh name="Dual_Monitors_on_sit-stand_arm|group329542522|Dupli|_2" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group329542522|Dupli|_2'].geometry} material={materials['mat23.015']} />
            </group>
            <mesh name="Dual_Monitors_on_sit-stand_arm|group451364077|Dupli|20" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group451364077|Dupli|20'].geometry} material={materials['mat22.010']} />
            <mesh name="Dual_Monitors_on_sit-stand_arm|group575146565|Dupli|6" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group575146565|Dupli|6'].geometry} material={materials['mat22.010']} />
            <group name="Dual_Monitors_on_sit-stand_arm|group576947092|Dupli|1">
              <mesh name="Dual_Monitors_on_sit-stand_arm|group576947092|Dupli|1_1" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group576947092|Dupli|1_1'].geometry} material={materials['mat22.010']} />
              <mesh name="Dual_Monitors_on_sit-stand_arm|group576947092|Dupli|1_2" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group576947092|Dupli|1_2'].geometry} material={materials['mat23.015']} />
            </group>
            <mesh name="Dual_Monitors_on_sit-stand_arm|group625259463|Dupli|4" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group625259463|Dupli|4'].geometry} material={materials['mat23.015']} />
            <mesh name="Dual_Monitors_on_sit-stand_arm|group710626981|Dupli|14" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group710626981|Dupli|14'].geometry} material={materials['mat22.010']} />
            <mesh name="Dual_Monitors_on_sit-stand_arm|group786212531|Dupli|21" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group786212531|Dupli|21'].geometry} material={materials['mat22.010']} />
            <group name="Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22">
              <mesh name="Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22_1" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22_1'].geometry} material={materials['mat22.010']} />
              <mesh name="Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22_2" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22_2'].geometry} material={materials['mat23.015']} />
              <mesh name="Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22_3" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22_3'].geometry} material={materials['mat21.012']} />
            </group>
            <mesh name="Dual_Monitors_on_sit-stand_arm|group929043094|Dupli|10" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group929043094|Dupli|10'].geometry} material={materials['mat22.010']} />
            <mesh name="Dual_Monitors_on_sit-stand_arm|group974294459|Dupli|17" geometry={nodes['Dual_Monitors_on_sit-stand_arm|group974294459|Dupli|17'].geometry} material={materials['mat23.015']} position={[0, 0, -0.008]} />
          </group>
          <group name="Keyboard" position={[-0.284, 0.974, -6.705]} rotation={[-1.576, -0.001, 3.102]} scale={20.517}>
            <mesh name="Keyboard|group1030983910|Dupli|22" geometry={nodes['Keyboard|group1030983910|Dupli|22'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group1075691498|Dupli|58" geometry={nodes['Keyboard|group1075691498|Dupli|58'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group1149852049|Dupli|53" geometry={nodes['Keyboard|group1149852049|Dupli|53'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group1152190519|Dupli|19" geometry={nodes['Keyboard|group1152190519|Dupli|19'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group1180881246|Dupli|50" geometry={nodes['Keyboard|group1180881246|Dupli|50'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group1238060299|Dupli|28" geometry={nodes['Keyboard|group1238060299|Dupli|28'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group1238428394|Dupli|61" geometry={nodes['Keyboard|group1238428394|Dupli|61'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group1272091893|Dupli|35" geometry={nodes['Keyboard|group1272091893|Dupli|35'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group1316349499|Dupli|39" geometry={nodes['Keyboard|group1316349499|Dupli|39'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group1323238240|Dupli|32" geometry={nodes['Keyboard|group1323238240|Dupli|32'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group145618305|Dupli|23" geometry={nodes['Keyboard|group145618305|Dupli|23'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group1486350934|Dupli|63" geometry={nodes['Keyboard|group1486350934|Dupli|63'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group150579309|Dupli|11" geometry={nodes['Keyboard|group150579309|Dupli|11'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group1529968652|Dupli|6" geometry={nodes['Keyboard|group1529968652|Dupli|6'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group1571332333|Dupli|33" geometry={nodes['Keyboard|group1571332333|Dupli|33'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group1581414308|Dupli|8" geometry={nodes['Keyboard|group1581414308|Dupli|8'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group1589752359|Dupli|26" geometry={nodes['Keyboard|group1589752359|Dupli|26'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group1629393722|Dupli|64" geometry={nodes['Keyboard|group1629393722|Dupli|64'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group1629609685|Dupli|21" geometry={nodes['Keyboard|group1629609685|Dupli|21'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group1675960081|Dupli|12" geometry={nodes['Keyboard|group1675960081|Dupli|12'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group1740918352|Dupli|46" geometry={nodes['Keyboard|group1740918352|Dupli|46'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group1753917514|Dupli|5" geometry={nodes['Keyboard|group1753917514|Dupli|5'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group1754683637|Dupli|40" geometry={nodes['Keyboard|group1754683637|Dupli|40'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group1764140354|Dupli|60" geometry={nodes['Keyboard|group1764140354|Dupli|60'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group1870575723|Dupli|65" geometry={nodes['Keyboard|group1870575723|Dupli|65'].geometry} material={materials['mat16.006']} />
            <mesh name="Keyboard|group1899843208|Dupli|36" geometry={nodes['Keyboard|group1899843208|Dupli|36'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group1956214489|Dupli|14" geometry={nodes['Keyboard|group1956214489|Dupli|14'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group196400395|Dupli|15" geometry={nodes['Keyboard|group196400395|Dupli|15'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group1976194690|Dupli|18" geometry={nodes['Keyboard|group1976194690|Dupli|18'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group205302596|Dupli|31" geometry={nodes['Keyboard|group205302596|Dupli|31'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group2074153597|Dupli|20" geometry={nodes['Keyboard|group2074153597|Dupli|20'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group2085389804|Dupli|57" geometry={nodes['Keyboard|group2085389804|Dupli|57'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group2091112366|Dupli|59" geometry={nodes['Keyboard|group2091112366|Dupli|59'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group2106755496|Dupli|4" geometry={nodes['Keyboard|group2106755496|Dupli|4'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group2146178072|Dupli|38" geometry={nodes['Keyboard|group2146178072|Dupli|38'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group252681800|Dupli|7" geometry={nodes['Keyboard|group252681800|Dupli|7'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group268332703|Dupli|44" geometry={nodes['Keyboard|group268332703|Dupli|44'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group287159489|Dupli|13" geometry={nodes['Keyboard|group287159489|Dupli|13'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group295085766|Dupli|9" geometry={nodes['Keyboard|group295085766|Dupli|9'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group311988427|Dupli|1" geometry={nodes['Keyboard|group311988427|Dupli|1'].geometry} material={materials['mat22.011']} position={[0, 0, -0.001]} />
            <mesh name="Keyboard|group34220672|Dupli|34" geometry={nodes['Keyboard|group34220672|Dupli|34'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group384612072|Dupli|10" geometry={nodes['Keyboard|group384612072|Dupli|10'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group418912012|Dupli|30" geometry={nodes['Keyboard|group418912012|Dupli|30'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group42243725|Dupli|37" geometry={nodes['Keyboard|group42243725|Dupli|37'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group425587018|Dupli|" geometry={nodes['Keyboard|group425587018|Dupli|'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group449779970|Dupli|3" geometry={nodes['Keyboard|group449779970|Dupli|3'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group45382983|Dupli|52" geometry={nodes['Keyboard|group45382983|Dupli|52'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group475225180|Dupli|41" geometry={nodes['Keyboard|group475225180|Dupli|41'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group573547017|Dupli|49" geometry={nodes['Keyboard|group573547017|Dupli|49'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group588539140|Dupli|47" geometry={nodes['Keyboard|group588539140|Dupli|47'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group601803475|Dupli|25" geometry={nodes['Keyboard|group601803475|Dupli|25'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group616518658|Dupli|56" geometry={nodes['Keyboard|group616518658|Dupli|56'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group687259746|Dupli|51" geometry={nodes['Keyboard|group687259746|Dupli|51'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group706802639|Dupli|17" geometry={nodes['Keyboard|group706802639|Dupli|17'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group729811280|Dupli|48" geometry={nodes['Keyboard|group729811280|Dupli|48'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group77921105|Dupli|42" geometry={nodes['Keyboard|group77921105|Dupli|42'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group790925258|Dupli|54" geometry={nodes['Keyboard|group790925258|Dupli|54'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group801095923|Dupli|29" geometry={nodes['Keyboard|group801095923|Dupli|29'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group806343109|Dupli|27" geometry={nodes['Keyboard|group806343109|Dupli|27'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group826580911|Dupli|24" geometry={nodes['Keyboard|group826580911|Dupli|24'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group873458270|Dupli|55" geometry={nodes['Keyboard|group873458270|Dupli|55'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group873558583|Dupli|62" geometry={nodes['Keyboard|group873558583|Dupli|62'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group877249531|Dupli|66" geometry={nodes['Keyboard|group877249531|Dupli|66'].geometry} material={materials['mat9.002']} />
            <mesh name="Keyboard|group954813675|Dupli|16" geometry={nodes['Keyboard|group954813675|Dupli|16'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group96314515|Dupli|2" geometry={nodes['Keyboard|group96314515|Dupli|2'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group96968687|Dupli|43" geometry={nodes['Keyboard|group96968687|Dupli|43'].geometry} material={materials['mat21.013']} />
            <mesh name="Keyboard|group993315105|Dupli|45" geometry={nodes['Keyboard|group993315105|Dupli|45'].geometry} material={materials['mat21.013']} />
          </group>
          <group name="Mug_With_Office_Tool" position={[-0.805, 0.937, -6.105]} rotation={[-Math.PI / 2, 0, 0]} scale={129.646}>
            <mesh name="Mug_With_Office_Tool|Mug_with_office_tools|Dupli|" geometry={nodes['Mug_With_Office_Tool|Mug_with_office_tools|Dupli|'].geometry} material={materials['Material.015']} scale={100} />
          </group>
          <group name="Notebook" position={[0.255, 0.942, -6.492]} rotation={[-Math.PI / 2, 0, -2.857]} scale={3.1}>
            <group name="Notebook|Notebook_Cube041|Dupli|">
              <mesh name="Notebook|Notebook_Cube041|Dupli|_1" geometry={nodes['Notebook|Notebook_Cube041|Dupli|_1'].geometry} material={materials['FFEB3B.002']} />
              <mesh name="Notebook|Notebook_Cube041|Dupli|_2" geometry={nodes['Notebook|Notebook_Cube041|Dupli|_2'].geometry} material={materials['795548.003']} />
              <mesh name="Notebook|Notebook_Cube041|Dupli|_3" geometry={nodes['Notebook|Notebook_Cube041|Dupli|_3'].geometry} material={materials['F44336.006']} />
            </group>
          </group>
          <group name="Soda001" position={[-1.161, 0.942, -6.524]} rotation={[-Math.PI / 2, 0, 0]} scale={18.63}>
            <group name="Soda001|Soda|Dupli|" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh name="Soda001|Soda|Dupli|_1" geometry={nodes['Soda001|Soda|Dupli|_1'].geometry} material={materials['White.005']} />
              <mesh name="Soda001|Soda|Dupli|_2" geometry={nodes['Soda001|Soda|Dupli|_2'].geometry} material={materials['Red.002']} />
            </group>
          </group>
          <group name="Calendar-8GqQAqxi3qk" position={[-1.101, 0.942, -6.167]} rotation={[-Math.PI / 2, 0, 2.753]} scale={1.243}>
            <mesh name="Calendar-8GqQAqxi3qk_1" geometry={nodes['Calendar-8GqQAqxi3qk_1'].geometry} material={materials.Calendar_Texture} />
            <mesh name="Calendar-8GqQAqxi3qk_2" geometry={nodes['Calendar-8GqQAqxi3qk_2'].geometry} material={materials.Calendar_Aquamarine} />
            <mesh name="Calendar-8GqQAqxi3qk_3" geometry={nodes['Calendar-8GqQAqxi3qk_3'].geometry} material={materials.Calendar_Ivory} />
            <mesh name="Calendar-8GqQAqxi3qk_4" geometry={nodes['Calendar-8GqQAqxi3qk_4'].geometry} material={materials.FrontColor} />
          </group>
          <group name="Desk" position={[-0.456, 0, -6.39]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
            <mesh name="Desk_1" geometry={nodes.Desk_1.geometry} material={materials['BlackCoatSteel.001']} />
            <mesh name="Desk_2" geometry={nodes.Desk_2.geometry} material={materials['GrayPlastic.001']} />
            <mesh name="Desk_3" geometry={nodes.Desk_3.geometry} material={materials['WhiteSteelScrew.001']} />
            <mesh name="Desk_4" geometry={nodes.Desk_4.geometry} material={materials['BlackPlastic.001']} />
            <mesh name="Desk_5" geometry={nodes.Desk_5.geometry} material={materials['BlackWood.001']} />
          </group>
          <mesh name="Mouse001" geometry={nodes.Mouse001.geometry} material={materials['Material.001']} position={[-0.935, 0.942, -6.808]} rotation={[-Math.PI / 2, 0, -2.69]} scale={[9999.999, 9999.999, 10000.001]} />
          <mesh name="Mousepad001" geometry={nodes.Mousepad001.geometry} material={materials.Mousepad} position={[-1.052, 0.944, -6.811]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[17.231, 20.977, 0.228]} />
          <group name="Office_Phone001" position={[0.338, 1.01, -6.188]} rotation={[0, 0.144, Math.PI]} scale={781.608}>
            <mesh name="Office_Phone001_1" geometry={nodes.Office_Phone001_1.geometry} material={materials['Light grey']} />
            <mesh name="Office_Phone001_2" geometry={nodes.Office_Phone001_2.geometry} material={materials['Grey Plastic']} />
            <mesh name="Office_Phone001_3" geometry={nodes.Office_Phone001_3.geometry} material={materials.Screen} />
            <mesh name="Office_Phone001_4" geometry={nodes.Office_Phone001_4.geometry} material={materials['Dark Grey Plastic']} />
          </group>
        </group>
        <group name="RootNode001" position={[0, 0.658, -0.801]} rotation={[-Math.PI, 0.1, -Math.PI]} scale={2.355} />
        <group name="RootNode002" position={[0.129, 0.272, -2.535]} scale={1.768}>
          <mesh name="Trashbin" geometry={nodes.Trashbin.geometry} material={materials['Material.002']} position={[0.219, -0.134, -0.541]} scale={100} />
        </group>
        <group name="RootNode003" position={[-0.34, 0.247, -0.92]} rotation={[Math.PI, -0.31, Math.PI]} scale={1.437}>
          <group name="OfficeChair" position={[-0.363, -0.165, 1.038]} rotation={[-1.578, -0.039, -0.212]} scale={100}>
            <mesh name="OfficeChair_1" geometry={nodes.OfficeChair_1.geometry} material={materials.Grey} />
            <mesh name="OfficeChair_2" geometry={nodes.OfficeChair_2.geometry} material={materials.Black} />
            <mesh name="OfficeChair_3" geometry={nodes.OfficeChair_3.geometry} material={materials.Chair} />
          </group>
        </group>
        <group name="RootNode005" position={[-2.611, 0.939, -4.05]} scale={1.574}>
          <group name="Shelf_Clutter" scale={100}>
            <mesh name="Shelf_Clutter_1" geometry={nodes.Shelf_Clutter_1.geometry} material={materials.mat22} />
            <mesh name="Shelf_Clutter_2" geometry={nodes.Shelf_Clutter_2.geometry} material={materials.mat17} />
            <mesh name="Shelf_Clutter_3" geometry={nodes.Shelf_Clutter_3.geometry} material={materials.mat15} />
            <mesh name="Shelf_Clutter_4" geometry={nodes.Shelf_Clutter_4.geometry} material={materials.mat1} />
            <mesh name="Shelf_Clutter_5" geometry={nodes.Shelf_Clutter_5.geometry} material={materials['mat21.005']} />
            <mesh name="Shelf_Clutter_6" geometry={nodes.Shelf_Clutter_6.geometry} material={materials.mat11} />
            <mesh name="Shelf_Clutter_7" geometry={nodes.Shelf_Clutter_7.geometry} material={materials['mat20.003']} />
            <mesh name="Shelf_Clutter_8" geometry={nodes.Shelf_Clutter_8.geometry} material={materials.mat16} />
            <mesh name="Shelf_Clutter_9" geometry={nodes.Shelf_Clutter_9.geometry} material={materials.mat24} />
            <mesh name="Shelf_Clutter_10" geometry={nodes.Shelf_Clutter_10.geometry} material={materials['mat8.003']} />
            <mesh name="Shelf_Clutter_11" geometry={nodes.Shelf_Clutter_11.geometry} material={materials['mat23.002']} />
            <mesh name="Shelf_Clutter_12" geometry={nodes.Shelf_Clutter_12.geometry} material={materials.mat7} />
            <mesh name="Shelf_Clutter_13" geometry={nodes.Shelf_Clutter_13.geometry} material={materials.mat12} />
            <mesh name="Shelf_Clutter_14" geometry={nodes.Shelf_Clutter_14.geometry} material={materials.mat4} />
            <mesh name="Shelf_Clutter_15" geometry={nodes.Shelf_Clutter_15.geometry} material={materials.mat10} />
          </group>
        </group>
        <group name="RootNode006" position={[1.744, 0, 1.704]} rotation={[Math.PI, -0.034, Math.PI]}>
          <group name="Couch_Small1" position={[0.395, 0, 0.013]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh name="Couch_Small1_1" geometry={nodes.Couch_Small1_1.geometry} material={materials.Couch_Blue} />
            <mesh name="Couch_Small1_2" geometry={nodes.Couch_Small1_2.geometry} material={materials['Black.002']} />
          </group>
        </group>
        <group name="group735054256" position={[-3.956, 0.197, 3.012]} rotation={[Math.PI, -0.047, Math.PI]} scale={8.086}>
          <mesh name="mesh735054256" geometry={nodes.mesh735054256.geometry} material={materials['mat23.001']} />
          <mesh name="mesh735054256_1" geometry={nodes.mesh735054256_1.geometry} material={materials.mat6} />
        </group>
        <mesh name="FiddleleafFigPottedPlant_mesh" geometry={nodes.FiddleleafFigPottedPlant_mesh.geometry} material={materials.FiddleleafFigPottedPlant_mat} position={[2.311, 0.034, -3.802]} scale={0.18} />
        <mesh name="Geo_Duck" geometry={nodes.Geo_Duck.geometry} material={materials.lambert2SG} position={[1.062, 1.757, 1.268]} rotation={[-Math.PI, 0.548, -Math.PI]} scale={0.018} />
        <group name="Node" position={[-2.64, 1.28, 2.144]} scale={2.113}>
          <mesh name="Node-Mesh" geometry={nodes['Node-Mesh'].geometry} material={materials['mat16.002']} />
          <mesh name="Node-Mesh_1" geometry={nodes['Node-Mesh_1'].geometry} material={materials['mat24.001']} />
          <mesh name="Node-Mesh_2" geometry={nodes['Node-Mesh_2'].geometry} material={materials.mat23} />
          <mesh name="Node-Mesh_3" geometry={nodes['Node-Mesh_3'].geometry} material={materials['mat18.001']} />
          <mesh name="Node-Mesh_4" geometry={nodes['Node-Mesh_4'].geometry} material={materials['mat17.001']} />
          <mesh name="Node-Mesh_5" geometry={nodes['Node-Mesh_5'].geometry} material={materials['mat10.001']} />
          <mesh name="Node-Mesh_6" geometry={nodes['Node-Mesh_6'].geometry} material={materials.mat13} />
        </group>
        <group name="Node001" position={[-2.598, 0.725, 2.092]} scale={1.076}>
          <mesh name="Node-Mesh001" geometry={nodes['Node-Mesh001'].geometry} material={materials.mat20} />
          <mesh name="Node-Mesh001_1" geometry={nodes['Node-Mesh001_1'].geometry} material={materials['mat15.001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/office.gltf')
